export const routes = {
  home: "/",
  adminAssessment: "/assessment",
  assessment: "/patient/assessment",
  booking: "/patient/booking",
  patientDashboard: "/patient/dashboard",
  results: "/patient/results",
  providerDashboard: "/provider/dashboard",
  login: "/login",
  register: "/register",
  forgotPassword: "/forgot-password",
  terms: "/terms",
  privacy: "/privacy",
  blog: "/blog",
  subscribe: "/subscribe",
  consultation: "/consultation",
  patientShop: "/patient/shop",
  patientProduct: "/patient/shop",
  patientCart: "/patient/shop/cart",
  patientCheckout: "/patient/shop/checkout",
  patientOrderConfirmation: "/patient/shop/order-confirmation",
  patientProfile: "/patient/profile",
  providerProfile: "/provider/profile",
  adminProfile: "/admin/profile",
  symptomTracker: "/patient/dashboard/symptom-tracker",
  providerAppointment: "/provider/appointments",
  admin: "/admin",
  adminPatients: "/admin/patients",
  adminAssessments: "/admin/assessments",
  adminAppointments: "/admin/appointments",
  adminSchedule: "/admin/schedule",
} as const;

export const navItems = [
  { label: "Shop", href: routes.patientShop },
  { label: "How It Works", href: "/#how-it-works" },
  { label: "Sign In", href: routes.login },
] as const;
